import type { Metadata } from "next";
import { Manrope, Fira_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/header";
import { cn } from "@/lib/utils";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const fira_sans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["latin"],
  weight:["400","500"]
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        //className={`${manrope.variable} ${fira_sans.variable}} antialiased`}
      className={cn('min-h-screen bg-background antialiased font-manrope font-fira-sans',manrope.variable,fira_sans.variable)}
      >
        <Header/>

        
        {children}
      </body>
    </html>
  );
}
